- name: Install Caldera on EC2 instance
  hosts: webservers
  become: yes

  tasks:
  - name: Install dependencies
    dnf:
      name:
        - python3
        - python3-pip
        - gcc
        - openssl-devel
        - python3-devel
        - git-all
      state: present
    become: yes
    become_method: sudo

  - name: Clone Caldera repository
    git:
        repo: https://github.com/mitre/caldera.git
        dest: /home/caldera
        recursive: yes
    become: yes
    become_method: sudo


  - name: Install Caldera requirements
    pip:
      requirements: /home/caldera/requirements.txt
      executable: pip3
    become: yes
    become_method: sudo

  - name: Start Caldera
    shell: 
      cmd: sudo nohup python3 server.py --insecure & #nohup detaches the process from the terminal and & keeps it open in the background
      chdir: /home/caldera
    async: 1
    poll: 0